version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
      - ./lib:/var/lib/redis
    command: ["redis-server --loadmodule /var/lib/redis/rebloom.so"]
networks:
  redis-net:
volumes:
  redis-data:
